name: Build and Run Tests

on:
  push:
    branches: [ "canon" ]
  pull_request:
    branches: [ "canon" ]

permissions:
  contents: read
  checks: write

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres:12.11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@79c4ce944ccd1fe6eef696124506a750cb9e98e7
      with:
        elixir-version: '1.13.4' # Define the elixir version [required]
        otp-version: '25.0.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build/test/lib/**
          !_build/test/lib/what_where_when/**
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix coveralls.github
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "_build/test/lib/what_where_when/test-junit-report.xml"
        comment_mode: off
